name: Build LaTeX

on:
  push:
  pull_request:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v4
        with:
          root_file: fi-pdflatex.tex
          compiler: latexmk
          args: -pdf -interaction=nonstopmode -synctex=1 -file-line-error

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: pdf
          path: fi-pdflatex.pdf
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: pdf

      - name: Prepare Pages
        run: |
          mkdir public
          cp *.pdf public/

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

      - name: Deploy to Pages
        uses: actions/deploy-pages@v4